{{- if and (not .Values.externalSecrets.enabled) (not .Values.vault.enabled)}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "allure-testops.fullname" . }}
  labels:
    app: {{ template "allure-testops.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  username: {{ .Values.username | b64enc | quote }}
{{- if .Values.password }}
  password: {{ .Values.password | b64enc | quote }}
{{- else }}
  password: {{ randAlphaNum 16 | b64enc | quote }}
{{- end }}
{{- if .Values.jwtSecret }}
  jwtSecret: {{ .Values.jwtSecret | b64enc | quote }}
{{- else }}
  jwtSecret: {{ randAlphaNum 64 | b64enc | quote }}
{{- end }}
{{- if .Values.cryptoPass }}
  cryptoPass: {{ .Values.cryptoPass | b64enc | quote }}
{{- else }}
  cryptoPass: {{ randAlphaNum 64 | b64enc | quote }}
{{- end }}
  rabbitUser: {{ .Values.rabbitmq.auth.username | b64enc | quote }}
  rabbitPass: {{ .Values.rabbitmq.auth.password | b64enc | quote }}
{{- if not .Values.postgresql.enabled }}
  uaaDbUser: {{ .Values.postgresql.external.uaaUsername | b64enc | quote }}
  uaaDbPass: {{ .Values.postgresql.external.uaaPassword | b64enc | quote }}
  reportDbUser: {{ .Values.postgresql.external.reportUsername | b64enc | quote }}
  reportDbPass: {{ .Values.postgresql.external.reportPassword | b64enc | quote }}
{{- else }}
  uaaDbUser: {{ .Values.postgresql.auth.username | b64enc | quote }}
  uaaDbPass: {{ .Values.postgresql.auth.password | b64enc | quote }}
  reportDbUser: {{ .Values.postgresql.auth.username | b64enc | quote }}
  reportDbPass: {{ .Values.postgresql.auth.password | b64enc | quote }}
{{- end }}
{{- if .Values.minio.enabled }}
  s3AccessKey: {{ .Values.minio.auth.rootUser | b64enc | quote }}
  s3SecretKey: {{ .Values.minio.auth.rootPassword | b64enc | quote }}
{{- else }}
  s3AccessKey: {{ .Values.fs.s3.accessKey | b64enc | quote }}
  s3SecretKey: {{ .Values.fs.s3.secretKey | b64enc | quote }}
{{- end}}
{{ if .Values.fs.s3.kms.enabled }}
  s3KmsKeyId: {{ .Values.fs.s3.kms.kmsKeyId | b64enc | quote }}
{{- end }}
  redisPass: {{ .Values.redis.auth.password | b64enc | quote }}
  clientId: {{ .Values.allure.auth.oidc.client.id | b64enc | quote }}
  clientSecret: {{ .Values.allure.auth.oidc.client.secret | b64enc | quote }}
  ldapUser: {{ .Values.allure.auth.ldap.auth.user | b64enc | quote }}
  ldapPass: {{ .Values.allure.auth.ldap.auth.pass | b64enc | quote }}
{{- if .Values.licenseKey }}
  licenseKey: {{ .Values.licenseKey | b64enc | quote }}
{{- end }}
{{- if .Values.subscriptionId }}
  subId: {{ .Values.subscriptionId | b64enc | quote }}
{{- end }}
{{- if .Values.licenseApiToken }}
  licenceApiToken: {{ .Values.licenseApiToken | b64enc | quote }}
{{- end }}
{{- if .Values.smtp.enabled }}
  smtpUsername: {{ .Values.smtp.username | b64enc | quote }}
  smtpPassword: {{ .Values.smtp.password | b64enc | quote }}
{{- end }}
{{- end }}
